// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: p2pbeacon.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendBeacon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agent   string `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SendBeacon) Reset() {
	*x = SendBeacon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2pbeacon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBeacon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBeacon) ProtoMessage() {}

func (x *SendBeacon) ProtoReflect() protoreflect.Message {
	mi := &file_p2pbeacon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBeacon.ProtoReflect.Descriptor instead.
func (*SendBeacon) Descriptor() ([]byte, []int) {
	return file_p2pbeacon_proto_rawDescGZIP(), []int{0}
}

func (x *SendBeacon) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *SendBeacon) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateRoute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agent string `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Route string `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
}

func (x *UpdateRoute) Reset() {
	*x = UpdateRoute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2pbeacon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoute) ProtoMessage() {}

func (x *UpdateRoute) ProtoReflect() protoreflect.Message {
	mi := &file_p2pbeacon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoute.ProtoReflect.Descriptor instead.
func (*UpdateRoute) Descriptor() ([]byte, []int) {
	return file_p2pbeacon_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateRoute) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *UpdateRoute) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

type EventWrapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//	*EventWrapper_B
	//	*EventWrapper_R
	Msg isEventWrapper_Msg `protobuf_oneof:"msg"`
}

func (x *EventWrapper) Reset() {
	*x = EventWrapper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2pbeacon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventWrapper) ProtoMessage() {}

func (x *EventWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_p2pbeacon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventWrapper.ProtoReflect.Descriptor instead.
func (*EventWrapper) Descriptor() ([]byte, []int) {
	return file_p2pbeacon_proto_rawDescGZIP(), []int{2}
}

func (m *EventWrapper) GetMsg() isEventWrapper_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *EventWrapper) GetB() *SendBeacon {
	if x, ok := x.GetMsg().(*EventWrapper_B); ok {
		return x.B
	}
	return nil
}

func (x *EventWrapper) GetR() *UpdateRoute {
	if x, ok := x.GetMsg().(*EventWrapper_R); ok {
		return x.R
	}
	return nil
}

type isEventWrapper_Msg interface {
	isEventWrapper_Msg()
}

type EventWrapper_B struct {
	B *SendBeacon `protobuf:"bytes,1,opt,name=b,proto3,oneof"`
}

type EventWrapper_R struct {
	R *UpdateRoute `protobuf:"bytes,2,opt,name=r,proto3,oneof"`
}

func (*EventWrapper_B) isEventWrapper_Msg() {}

func (*EventWrapper_R) isEventWrapper_Msg() {}

var File_p2pbeacon_proto protoreflect.FileDescriptor

var file_p2pbeacon_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x32, 0x70, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x70, 0x75, 0x62, 0x73, 0x75, 0x62, 0x22, 0x3c, 0x0a, 0x0a, 0x53, 0x65, 0x6e,
	0x64, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x39, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x22, 0x5e, 0x0a, 0x0c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x57, 0x72, 0x61, 0x70, 0x70,
	0x65, 0x72, 0x12, 0x22, 0x0a, 0x01, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x70, 0x75, 0x62, 0x73, 0x75, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x65, 0x61, 0x63, 0x6f,
	0x6e, 0x48, 0x00, 0x52, 0x01, 0x62, 0x12, 0x23, 0x0a, 0x01, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x70, 0x75, 0x62, 0x73, 0x75, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x48, 0x00, 0x52, 0x01, 0x72, 0x42, 0x05, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x75, 0x62, 0x73, 0x75, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_p2pbeacon_proto_rawDescOnce sync.Once
	file_p2pbeacon_proto_rawDescData = file_p2pbeacon_proto_rawDesc
)

func file_p2pbeacon_proto_rawDescGZIP() []byte {
	file_p2pbeacon_proto_rawDescOnce.Do(func() {
		file_p2pbeacon_proto_rawDescData = protoimpl.X.CompressGZIP(file_p2pbeacon_proto_rawDescData)
	})
	return file_p2pbeacon_proto_rawDescData
}

var file_p2pbeacon_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_p2pbeacon_proto_goTypes = []interface{}{
	(*SendBeacon)(nil),   // 0: pubsub.SendBeacon
	(*UpdateRoute)(nil),  // 1: pubsub.UpdateRoute
	(*EventWrapper)(nil), // 2: pubsub.EventWrapper
}
var file_p2pbeacon_proto_depIdxs = []int32{
	0, // 0: pubsub.EventWrapper.b:type_name -> pubsub.SendBeacon
	1, // 1: pubsub.EventWrapper.r:type_name -> pubsub.UpdateRoute
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_p2pbeacon_proto_init() }
func file_p2pbeacon_proto_init() {
	if File_p2pbeacon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_p2pbeacon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBeacon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2pbeacon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRoute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2pbeacon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventWrapper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_p2pbeacon_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*EventWrapper_B)(nil),
		(*EventWrapper_R)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_p2pbeacon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_p2pbeacon_proto_goTypes,
		DependencyIndexes: file_p2pbeacon_proto_depIdxs,
		MessageInfos:      file_p2pbeacon_proto_msgTypes,
	}.Build()
	File_p2pbeacon_proto = out.File
	file_p2pbeacon_proto_rawDesc = nil
	file_p2pbeacon_proto_goTypes = nil
	file_p2pbeacon_proto_depIdxs = nil
}
